### PR TITLE
Fixed #382.

### LINKED ISSUE #382: Build Failures on OpenBSD.
msgpack-c fails to build on OpenBSD. I am building the latest release (1.2.0) without  C++11 support.

Without any modifications and using GCC-4.2.1  it fails due to unrecognised flags:
```
FAILED: /usr/bin/c++    -std=c++03 -O2 -pipe    -DNDEBUG -I/usr/ports/pobj/msgpack-1.2.0/msgpack-c-cpp-1.2.0/. -I/usr/ports/pobj/msgpack-1.2.0/msgpack-c-cpp-1.2.0/include -Iinclude    -Wall -Wextra -Werror -Wno-mismatched-tags -g -O3 -MMD -MT example/cpp03/CMakeFiles/class_non_intrusive.dir/class_non_intrusive.cpp.o -MF example/cpp03/CMakeFiles/class_non_intrusive.dir/class_non_intrusive.cpp.o.d -o example/cpp03/CMakeFiles/class_non_intrusive.dir/class_non_intrusive.cpp.o -c /usr/ports/pobj/msgpack-1.2.0/msgpack-c-cpp-1.2.0/example/cpp03/class_non_intrusive.cpp
cc1plus: error: unrecognized command line option "-Wno-mismatched-tags"
cc1plus: error: unrecognized command line option "-std=c++03"
ninja: build stopped: subcommand failed.
```

So I guess you need a configure check to see if those are available.

If I patch away all of these flags (and `-O3 -g`):
```
FAILED: /usr/bin/c++    -O2 -pipe    -DNDEBUG -I/usr/ports/pobj/msgpack-1.2.0/msgpack-c-cpp-1.2.0/. -I/usr/ports/pobj/msgpack-1.2.0/msgpack-c-cpp-1.2.0/include -Iinclude -I/usr/local/include    -Wall -Wextra -Werror -MMD -MT test/CMakeFiles/raw.dir/raw.cpp.o -MF test/CMakeFiles/raw.dir/raw.cpp.o.d -o test/CMakeFiles/raw.dir/raw.cpp.o -c /usr/ports/pobj/msgpack-1.2.0/msgpack-c-cpp-1.2.0/test/raw.cpp
/usr/local/include/gtest/internal/gtest-internal.h: In function 'void GTestStreamToHelper(std::ostream*, const T&) [with T = msgpack::v1::type::raw_ref]':
/usr/local/include/gtest/gtest-message.h:116:   instantiated from 'testing::Message& testing::Message::operator<<(const T&) [with T = msgpack::v1::type::raw_ref]'
/usr/local/include/gtest/gtest.h:173:   instantiated from 'testing::internal::String testing::internal::StreamableToString(const T&) [with T = msgpack::v1::type::raw_ref]'
/usr/local/include/gtest/internal/gtest-internal.h:234:   instantiated from 'testing::internal::String testing::internal::FormatForFailureMessage(const T&) [with T = msgpack::v1::type::raw_ref]'
/usr/local/include/gtest/gtest.h:1171:   instantiated from 'testing::internal::String testing::internal::FormatForComparisonFailureMessage(const T1&, const T2&) [with T1 = msgpack::v1::type::raw_ref, T2 = msgpack::v1::type::raw_ref]'
/usr/local/include/gtest/gtest.h:1198:   instantiated from 'testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = msgpack::v1::type::raw_ref, T2 = msgpack::v1::type::raw_ref]'
/usr/local/include/gtest/gtest.h:1223:   instantiated from 'static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = msgpack::v1::type::raw_ref, T2 = msgpack::v1::type::raw_ref, bool lhs_is_null_literal = false]'
/usr/ports/pobj/msgpack-1.2.0/msgpack-c-cpp-1.2.0/test/raw.cpp:29:   instantiated from here
/usr/local/include/gtest/internal/gtest-internal.h:97: error: no match for 'operator<<' in '* os << val'
/usr/include/g++/ostream:112: note: candidates are: std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(std::basic_ostream<_CharT, _Traits>& (*)(std::basic_ostream<_CharT, _Traits>&)) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:121: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(std::basic_ios<_CharT, _Traits>& (*)(std::basic_ios<_CharT, _Traits>&)) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:131: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(std::ios_base& (*)(std::ios_base&)) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:169: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(long int) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:173: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(long unsigned int) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:177: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(bool) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/bits/ostream.tcc:92: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(short int) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:184: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(short unsigned int) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/bits/ostream.tcc:106: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(int) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:195: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(unsigned int) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:204: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(long long int) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:208: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(long long unsigned int) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:213: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(double) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:217: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(float) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:225: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(long double) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:229: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(const void*) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/bits/ostream.tcc:120: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(std::basic_streambuf<_CharT, _Traits>*) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/local/include/gtest/internal/gtest-internal.h: In function 'void GTestStreamToHelper(std::ostream*, const T&) [with T = msgpack::v1::type::v4raw_ref]':
/usr/local/include/gtest/gtest-message.h:116:   instantiated from 'testing::Message& testing::Message::operator<<(const T&) [with T = msgpack::v1::type::v4raw_ref]'
/usr/local/include/gtest/gtest.h:173:   instantiated from 'testing::internal::String testing::internal::StreamableToString(const T&) [with T = msgpack::v1::type::v4raw_ref]'
/usr/local/include/gtest/internal/gtest-internal.h:234:   instantiated from 'testing::internal::String testing::internal::FormatForFailureMessage(const T&) [with T = msgpack::v1::type::v4raw_ref]'
/usr/local/include/gtest/gtest.h:1171:   instantiated from 'testing::internal::String testing::internal::FormatForComparisonFailureMessage(const T1&, const T2&) [with T1 = msgpack::v1::type::v4raw_ref, T2 = msgpack::v1::type::v4raw_ref]'
/usr/local/include/gtest/gtest.h:1198:   instantiated from 'testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = msgpack::v1::type::v4raw_ref, T2 = msgpack::v1::type::v4raw_ref]'
/usr/local/include/gtest/gtest.h:1223:   instantiated from 'static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = msgpack::v1::type::v4raw_ref, T2 = msgpack::v1::type::v4raw_ref, bool lhs_is_null_literal = false]'
/usr/ports/pobj/msgpack-1.2.0/msgpack-c-cpp-1.2.0/test/raw.cpp:142:   instantiated from here
/usr/local/include/gtest/internal/gtest-internal.h:97: error: no match for 'operator<<' in '* os << val'
/usr/include/g++/ostream:112: note: candidates are: std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(std::basic_ostream<_CharT, _Traits>& (*)(std::basic_ostream<_CharT, _Traits>&)) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:121: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(std::basic_ios<_CharT, _Traits>& (*)(std::basic_ios<_CharT, _Traits>&)) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:131: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(std::ios_base& (*)(std::ios_base&)) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:169: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(long int) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:173: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(long unsigned int) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:177: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(bool) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/bits/ostream.tcc:92: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(short int) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:184: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(short unsigned int) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/bits/ostream.tcc:106: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(int) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:195: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(unsigned int) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:204: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(long long int) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:208: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(long long unsigned int) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:213: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(double) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:217: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(float) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:225: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(long double) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/ostream:229: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(const void*) [with _CharT = char, _Traits = std::char_traits<char>]
/usr/include/g++/bits/ostream.tcc:120: note:                 std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(std::basic_streambuf<_CharT, _Traits>*) [with _CharT = char, _Traits = std::char_traits<char>]
ninja: build stopped: subcommand failed.
```

I then tried with GCC-4.9.3 without any patches and got:
```
FAILED: /usr/ports/pobj/msgpack-1.2.0/bin/c++    -std=c++03 -O2 -pipe    -DNDEBUG -I/usr/ports/pobj/msgpack-1.2.0/msgpack-c-cpp-1.2.0/. -I/usr/ports/pobj/msgpack-1.2.0/msgpack-c-cpp-1.2.0/include -Iinclude -I/usr/local/include    -Wall -Wextra -Werror -Wno-mismatched-tags -g -O3 -MMD -MT test/CMakeFiles/msgpack_container.dir/msgpack_container.cpp.o -MF test/CMakeFiles/msgpack_container.dir/msgpack_container.cpp.o.d -o test/CMakeFiles/msgpack_container.dir/msgpack_container.cpp.o -c /usr/ports/pobj/msgpack-1.2.0/msgpack-c-cpp-1.2.0/test/msgpack_container.cpp
In file included from /usr/local/include/gtest/gtest-param-test.h:159:0,
                 from /usr/local/include/gtest/gtest.h:59,
                 from /usr/ports/pobj/msgpack-1.2.0/msgpack-c-cpp-1.2.0/test/msgpack_container.cpp:14:
/usr/local/include/gtest/internal/gtest-param-util-generated.h: In instantiation of 'testing::internal::ValueArray2<T1, T2>::operator testing::internal::ParamGenerator<T>() const [with T = bool; T1 = bool; T2 = bool]':
/usr/local/include/gtest/gtest-param-test.h:1186:28:   required from here
/usr/local/include/gtest/internal/gtest-param-util-generated.h:80:26: error: 'ValuesIn' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
     return ValuesIn(array);
                          ^
In file included from /usr/local/include/gtest/gtest.h:59:0,
                 from /usr/ports/pobj/msgpack-1.2.0/msgpack-c-cpp-1.2.0/test/msgpack_container.cpp:14:
/usr/local/include/gtest/gtest-param-test.h:288:58: note: 'template<class Container> testing::internal::ParamGenerator<typename Container::value_type> testing::ValuesIn(const Container&)' declared here, later in the translation unit
 internal::ParamGenerator<typename Container::value_type> ValuesIn(
                                                          ^
cc1plus: error: unrecognized command line option "-Wno-mismatched-tags" [-Werror]
cc1plus: all warnings being treated as errors
```

The docs say it should work with GCC>=4.1, so I would expect the build to succeed for both versions I tried.

Cheers

### PR DESCRIPTION
**Pull request by redboltz**
Fixed warnings on gcc 4.1.2.
Added gcc version checking for adding -std=c++03 flag.

### CODE REVIEW

**Comment by jpetso** [comment]
Just something that I saw when looking at this patch: `-g` shouldn't be specified in the CXXFLAGS, right? That's the job of CMAKE_BUILD_TYPE which is passed to `cmake` on the command line?

**Comment by redboltz** [comment]
True. -g should be added on debug build only. When I run cmake as a Relase mode as follows:

```
cmake -DMSGPACK_CXX11=ON -DMSGPACK_BOOST=ON -DCMAKE_BUILD_TYPE=Release .. 
```

-g option is added. It's not good.

I think that I should use the following variables:

```
CMAKE_CXX_FLAGS_DEBUG 
compiler flags for compiling a debug build from C++ sources.
CMAKE_CXX_FLAGS_RELEASE 
compiler flags for compiling a release build from C++ sources.
```
https://cmake.org/Wiki/CMake_Useful_Variables#Compilers_and_Tools

Also I think that the optimization option -O0 is an appropriate default value for debug build. 

Those are the different topic from the issue. So I think that the topic should be treated on the separate PR or issue.

**Comment by redboltz** [comment]
I merge the PR and close. I added the new issue #405
