### ISSUE TITLE
Various compilation errors from variant.hpp with mSVC 19.29 when including msgpack with std::variant support

### ISSUE THREAD

**Issue by mxmlnkn** [msgpack/msgpack-c#1161]
I get the following compilation errors when compiling on Windows.

```
MSVC 19.29.30154.0

C:\PROGRA~2\MIB055~1\2019\PROFES~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  /nologo /TP \
    -DMSGPACK_DEFAULT_API_VERSION=3 -DMSGPACK_DISABLE_LEGACY_NIL -DMSGPACK_NO_BOOST \
    -DMSGPACK_USE_STD_VARIANT_ADAPTOR -DNOGDI -DNOMINMAX \
    -DUNICODE -DWIN32 -DWIN64 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D_UNICODE -D_WIN64 \
    -IC:\Users\build\program \
    -external:IC:\Qt\6.5.6\include\QtCore \
    -external:IC:\Qt\6.5.6\include \
    -external:IC:\Qt\6.5.6\mkspecs\win32-msvc \
    -external:W0 /DWIN32 /D_WINDOWS /EHsc /Zi /O2 /Ob1 /DNDEBUG -std:c++20 -MD /bigobj /W4 \
    /experimental:external /external:W0 -Zc:__cplusplus -permissive- -utf-8 /Zc:__cplusplus /showIncludes \
    /FS -c C:\Users\build\program\file-including-msgpack.cpp

C:\Users\build\msgpack/v1/adaptor/cpp17/variant.hpp(73): error C2059: syntax error: '...'
C:\Users\build\msgpack/v1/adaptor/cpp17/variant.hpp(73): error C2062: type 'unknown-type' unexpected
C:\Users\build\msgpack/v1/adaptor/cpp17/variant.hpp(73): error C2039: 'type': is not a member of '`global namespace''
C:\Users\build\msgpack/v1/adaptor/cpp17/variant.hpp(73): error C2332: 'struct': missing tag name
C:\Users\build\msgpack/v1/adaptor/cpp17/variant.hpp(73): error C3306: 'msgpack::v1::adaptor::<unnamed-tag>': unnamed class template is not allowed
```

The problem occurs with:

 - msgpack-cxx 6.1.0
 - msgpack-cxx 7.0.0

Msgpack-cxx is built from source configured like this:

```
cmake \
    -DMSGPACK_CXX20=ON \
    -DMSGPACK_USE_STD_VARIANT_ADAPTOR=ON \
    -DMSGPACK_USE_BOOST=OFF \
    -DBUILD_SHARED_LIBS=OFF \
    -DMSGPACK_BUILD_EXAMPLES=OFF \
    -DMSGPACK_BUILD_DOCS=OFF
```

The code in question:

https://github.com/msgpack/msgpack-c/blob/44c0f705c9a60217d7e07de844fb13ce4c1c1e6e/include/msgpack/v1/adaptor/cpp17/variant.hpp#L73

**Comment by redboltz** [comment]
A syntax error is reported.

```
C:\Users\build\msgpack/v1/adaptor/cpp17/variant.hpp(73): error C2059: syntax error: '...'
```

It is fold expressions.
See https://en.cppreference.com/w/cpp/language/fold.html

It seems that your compiler or options doesn't support it.
Updating the compiler version or set appropriate options (if it exists) would solve the issue.

**Comment by mxmlnkn** [comment]
Thank you. It is weird though that [fold expressions](https://en.cppreference.com/w/cpp/compiler_support/17.html#C.2B.2B17_library_features) are reported to work with MSVC 19.12+. Well, I guess I'll have to update. Feel free to close this issue.
